### ISSUE TITLE
Missing "import time"

### ISSUE THREAD

**Issue by yukuku** [the-glu/telegram_backup#2]
After the last messages printed that seems to require slowing down:

```
ERROR:pytg.sender:Result parser does not allow exceptions, but we got one: 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 426, in _do_send
    answer = self.s.recv(1)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 252, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 359, in _do_command
    result = self._do_send(request, answer_timeout=answer_timeout, retry_connect=retry_connect)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 449, in _do_send
    raise NoResponse(command)
pytg.exceptions.NoResponse:  [disable_preview] history writory 250 2500

WARNING:root:Slowing down...
INFO:root:Loading, offset 2500
ERROR:pytg.sender:Result parser does not allow exceptions, but we got one: 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 426, in _do_send
    answer = self.s.recv(1)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 252, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 359, in _do_command
    result = self._do_send(request, answer_timeout=answer_timeout, retry_connect=retry_connect)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 449, in _do_send
    raise NoResponse(command)
pytg.exceptions.NoResponse:  [disable_preview] history writory 250 2500

WARNING:root:Slowing down...
```

An error occured:

```
Traceback (most recent call last):
  File "dump.py", line 157, in <module>
    work_on_dialog(d)
  File "dump.py", line 73, in work_on_dialog
    time.sleep(5)
NameError: name 'time' is not defined
```

Adding `import time` fixes this.

**Comment by the-glu** [comment]
My fault, I mixed two versions of the script :(

Thanks for the report ^^
