### ISSUE TITLE
"Result parser does not allow exceptions." in load_document

### ISSUE THREAD

**Issue by yukuku** [the-glu/telegram_backup#3]
Got this exception when running `dump.py`

```
ERROR:pytg.sender:Result parser does not allow exceptions, but we got one: 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 426, in _do_send
    answer = self.s.recv(1)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 250, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=result_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 359, in _do_command
    result = self._do_send(request, answer_timeout=answer_timeout, retry_connect=retry_connect)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 449, in _do_send
    raise NoResponse(command)
pytg.exceptions.NoResponse:  [disable_preview] load_document 27361

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 426, in _do_send
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 250, in execute_function
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 359, in _do_command
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 449, in _do_send
pytg.exceptions.NoResponse:  [disable_preview] load_document 27361


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dump.py", line 158, in <module>
    work_on_dialog(d)
  File "dump.py", line 118, in work_on_dialog
    result = x.load_document(message['id'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 548, in command_alias
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 259, in execute_function
pytg.exceptions.IllegalResponseException: Result parser does not allow exceptions.
INFO:pytg.sender:Quit Sending. Not allowing sending anymore.
WARNING:pytg.sender:Terminating currently sending request.
INFO:pytg.sender:Currently not Sending.
```

**Comment by the-glu** [comment]
Is the document being downloaded in telegram-cli ? (There is a small percentage in red)

**Comment by yukuku** [comment]
Yes, in telegram-cli there is a red indicator. When the exception above occurs, the red indicator percentage still increases. After it reaches 100%, nothing happens (since the above exception has occured and dump.py already terminates).

**Comment by the-glu** [comment]
Ok. If you just run the script again, does it works ? I think telegram-cli cache the file and he is too big to download :|

**Comment by yukuku** [comment]
No, it does not work after repeated attempts. It seems yes, the file is too
big to download, but eventually telegram-cli finishes downloading, but the
dump.py (or probably pytg) thinks that it is already timed out.

**Comment by the-glu** [comment]
Ok, I will check if I can increase the timeout

**Comment by the-glu** [comment]
Should be working for the moment :)

**Comment by yukuku** [comment]
Thanks! It seems working now.
