### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by rizaumami** [the-glu/telegram_backup#6]
I've tried `telegram_backup` so many times to backup my chat, but always failed.

This is when `sudo python setup.py install` for the first time:

``` bash
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from pytg import VERSION
  File "/home/iza/github/pytg/pytg/__init__.py", line 9, in <module>
    from luckydonaldUtils.encoding import to_unicode as u
ImportError: No module named luckydonaldUtils.encoding
```

Then, when `sudo pip install luckydonald-utils` to install dependencies:

``` bash
Downloading/unpacking luckydonald-utils
  Downloading luckydonald-utils-0.27.tar.gz
  Running setup.py (path:/tmp/pip-build-9OFyYL/luckydonald-utils/setup.py) egg_info for package luckydonald-utils

Requirement already satisfied (use --upgrade to upgrade): pip in /usr/lib/python2.7/dist-packages (from luckydonald-utils)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from luckydonald-utils)
Installing collected packages: luckydonald-utils
  Running setup.py install for luckydonald-utils
      File "/usr/local/lib/python2.7/dist-packages/luckydonaldUtils/logger/py3.py", line 6
        def success(self, msg, *args, exc_info=False, **kwargs):
                                             ^
    SyntaxError: invalid syntax

      File "/usr/local/lib/python2.7/dist-packages/luckydonaldUtils/time/py3.py", line 10
        def get_local_time(time:datetime.datetime, time_zone:str=None) -> datetime.datetime:
                               ^
    SyntaxError: invalid syntax


Successfully installed luckydonald-utils
Cleaning up...
```

When reinstall with `sudo python setup.py install`:

``` bash
/usr/lib/python2.7/dist-packages/setuptools/dist.py:294: UserWarning: The version specified ('0.4.1d') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
creating pytg.egg-info
writing requirements to pytg.egg-info/requires.txt
writing pytg.egg-info/PKG-INFO
writing top-level names to pytg.egg-info/top_level.txt
writing dependency_links to pytg.egg-info/dependency_links.txt
writing manifest file 'pytg.egg-info/SOURCES.txt'
reading manifest file 'pytg.egg-info/SOURCES.txt'
writing manifest file 'pytg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pytg
copying pytg/__init__.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/argument_types.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/exceptions.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/fix_msg_array.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/fix_plain_output.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/receiver.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/result_parser.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/sender.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/test.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/this_py_version.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/utils.py -> build/lib.linux-x86_64-2.7/pytg
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/__init__.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/argument_types.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/exceptions.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/fix_msg_array.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/fix_plain_output.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/receiver.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/result_parser.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/sender.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/test.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/this_py_version.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/utils.py -> build/bdist.linux-x86_64/egg/pytg
byte-compiling build/bdist.linux-x86_64/egg/pytg/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/argument_types.py to argument_types.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/fix_msg_array.py to fix_msg_array.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/fix_plain_output.py to fix_plain_output.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/receiver.py to receiver.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/result_parser.py to result_parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/sender.py to sender.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/test.py to test.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/this_py_version.py to this_py_version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/utils.py to utils.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pytg-0.4.1d-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pytg-0.4.1d-py2.7.egg
Copying pytg-0.4.1d-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pytg 0.4.1d to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pytg-0.4.1d-py2.7.egg
Processing dependencies for pytg===0.4.1d
Searching for DictObject
Reading https://pypi.python.org/simple/DictObject/
Best match: DictObject 0.1.2
Downloading https://pypi.python.org/packages/source/D/DictObject/DictObject-0.1.2.tar.gz#md5=b4f77e9c9ca1089efdeb0dd155860483
Processing DictObject-0.1.2.tar.gz
Writing /tmp/easy_install-epdOiq/DictObject-0.1.2/setup.cfg
Running DictObject-0.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-epdOiq/DictObject-0.1.2/egg-dist-tmp-HeSsmU
zip_safe flag not set; analyzing archive contents...
Moving DictObject-0.1.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding DictObject 0.1.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/DictObject-0.1.2-py2.7.egg
Searching for luckydonald-utils==0.27
Best match: luckydonald-utils 0.27
Adding luckydonald-utils 0.27 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for setuptools==18.4
Best match: setuptools 18.4
setuptools 18.4 is already the active version in easy-install.pth
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for pip==1.5.6
Best match: pip 1.5.6
pip 1.5.6 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for pytg===0.4.1d
```

Run `telegram-cli` as a daemon, then `python dump.py`:

``` bash
Traceback (most recent call last):
  File "dump.py", line 164, in <module>
    for d in build_dialogs_list():
  File "dump.py", line 28, in build_dialogs_list
    res = x.dialog_list(100, len(base_list))
  File "build/bdist.linux-x86_64/egg/pytg/sender.py", line 548, in command_alias
  File "build/bdist.linux-x86_64/egg/pytg/sender.py", line 256, in execute_function
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <pytg.result_parser.List object at 0x7f2f4ab766d0> is not a Python function
INFO:pytg.sender:Quit Sending. Not allowing sending anymore.
WARNING:pytg.sender:Terminating currently sending request.
INFO:pytg.sender:Currently not Sending.
```

Tried with python 3; `python3 dump.py`

``` bash
Traceback (most recent call last):
  File "dump.py", line 1, in <module>
    from pytg import sender
ImportError: No module named 'pytg'
```

I'm not a programmer and this python version things is confusing, would love to get newbie friendly install for this script.

**Comment by the-glu** [comment]
The packages for python2 and python3 aren't the same, so you only installed _pytg_ for python2.

Can you try using a python3 version of pip ? It's can be `pip3` on your system.

You will probably run in the same issues with _luckydonald-utils_, it's an error in _pytg_, just install it first as you did for python2.

**Comment by rizaumami** [comment]
Thank you, it's running now :smile:
